apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort  # Better for Minikube
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900  # Fixed port for easier access
      name: api
    - port: 9090
      targetPort: 9090
      nodePort: 30909  # Fixed port for easier access
      name: console
  selector:
    app: minio
