name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev-branch  # or the branch you want to target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t abemdxb/ml-in-production-getting-started:latest .

      # Uncomment and configure the following steps if you want to push the image

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push abemdxb/ml-in-production:latest
